message:
  initial:
    title:
      text: "–ê—Å—Å–∏—Å—Ç–µ–Ω—Ç –¥–ª—è –ø—Ä–æ–≤–µ—Ä–∫–∏ –æ—Ç—á–µ—Ç–æ–≤"
      color: 0x3498db
    description:
      text: "üëã –Ø - –±–æ—Ç, –∫–æ—Ç–æ—Ä—ã–π –∏—Å–ø–æ–ª—å–∑—É–µ—Ç –ò–ò –¥–ª—è –ø—Ä–æ–≤–µ—Ä–∫–∏ –æ—Ç—á–µ—Ç–æ–≤.
            –¢—ã –º–æ–∂–µ—à—å –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –º–µ–Ω—è, —á—Ç–æ–±—ã –≤—ã–ø–æ–ª–Ω–∏—Ç—å —Å–∞–º–æ–ø—Ä–æ–≤–µ—Ä–∫—É –ø–µ—Ä–µ–¥ –ø—É–±–ª–∏–∫–∞—Ü–∏–µ–π –æ—Ç—á–µ—Ç–∞. 
            –≠—Ç–æ –ø–æ–º–æ–∂–µ—Ç —Å–Ω–∏–∑–∏—Ç—å –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –≤–æ–ø—Ä–æ—Å–æ–≤ –∫–∞–∫ —É —Ç–≤–æ–µ–≥–æ —Å—É–ø–µ—Ä–≤–∞–π–∑–µ—Ä–∞, —Ç–∞–∫ –∏ —É –û–í–†


            ‚ÑπÔ∏è –ï—Å–ª–∏ —Ç—ã —Å—Ç–æ–ª–∫–Ω—É–ª—Å—è —Å –æ—à–∏–±–∫–∞–º–∏, —Ö–æ—á–µ—à—å –ø—Ä–µ–¥–ª–æ–∂–∏—Ç—å —É–ª—É—á—à–µ–Ω–∏—è –∏–ª–∏ –ø–æ–ª—É—á–∏—Ç—å –ø–æ–º–æ—â—å - 
            –Ω–∞–ø–∏—à–∏ –≤ –õ–° <@337950212016439327>


            ‚¨áÔ∏è –ù–∞–∂–º–∏ –Ω–∞ –∫–Ω–æ–ø–∫—É –Ω–∏–∂–µ, —á—Ç–æ–±—ã –ø—Ä–∏—Å—Ç—É–ø–∏—Ç—å –∫ –ø—Ä–æ–≤–µ—Ä–∫–µ –∏–ª–∏ —É–∑–Ω–∞—Ç—å –∫–∞–∫ –≤—Å–µ —ç—Ç–æ —Ä–∞–±–æ—Ç–∞–µ—Ç"
    image:
      url: "https://i.ibb.co/MxKqyByh/Ai-Report-Helper.png"
    button:
      start:
        label: "–ù–∞—á–∞—Ç—å –ø—Ä–æ–≤–µ—Ä–∫—É"
      help:
        label: "–ò–Ω—Å—Ç—Ä—É–∫—Ü–∏—è"

  check_result:
    title:
      text: "‚ÑπÔ∏è –ë–æ—Ç –Ω–∞—Ö–æ–¥–∏—Ç—Å—è –≤ —Å—Ç–∞–¥–∏–∏ —Ä–∞–∑—Ä–∞–±–æ—Ç–∫–∏. 
            –ï—Å–ª–∏ —Ç—ã —Å—Ç–æ–ª–∫–Ω—É–ª—Å—è —Å –Ω–µ–ø—Ä–∞–≤–∏–ª—å–Ω—ã–º–∏ –∏–ª–∏ —Å—Ç—Ä–∞–Ω–Ω—ã–º–∏ —Ä–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏—è–º–∏ - 
            –Ω–∞–ø–∏—à–∏ –≤ –õ–° dre_og
            
            
            üìã –†–µ–∑—É–ª—å—Ç–∞—Ç –ø—Ä–æ–≤–µ—Ä–∫–∏ –æ—Ç—á–µ—Ç–∞"
      color: 0x3498db
    description:
      text: "–û—Å—Ç–∞–ª–æ—Å—å –ø—Ä–æ–≤–µ—Ä–æ–∫:"
    button:
      nav_back:
        label: "‚èÆ –ù–∞–∑–∞–¥"
      nav_next:
        label: "‚è≠ –í–ø–µ—Ä–µ–¥"
      finish:
        label: "–ó–∞–≤–µ—Ä—à–∏—Ç—å —Å–µ—Å—Å–∏—é"


  help:
    description:
      text: "üìò **–ò–Ω—Å—Ç—Ä—É–∫—Ü–∏—è –ø–æ –∏—Å–ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—é:**
            
            1Ô∏è. –ù–∞–∂–º–∏ –Ω–∞ –∫–Ω–æ–ø–∫—É, —á—Ç–æ–±—ã –Ω–∞—á–∞—Ç—å –ø—Ä–æ–≤–µ—Ä–∫—É
            
            2Ô∏è. –Ø –Ω–∞–ø–∏—à—É —Ç–µ–±–µ –≤ –ª–∏—á–Ω—ã–µ —Å–æ–æ–±—â–µ–Ω–∏—è. –ï—Å–ª–∏ —Å–æ–æ–±—â–µ–Ω–∏–µ –Ω–µ –ø—Ä–∏—à–ª–æ - 
            –ø—Ä–æ–≤–µ—Ä—å, —á—Ç–æ —É —Ç–µ–±—è —Ä–∞–∑—Ä–µ—à–µ–Ω—ã –õ–° –æ—Ç —É—á–∞—Å—Ç–Ω–∏–∫–æ–≤ —Å–µ—Ä–≤–µ—Ä–∞
            
            3Ô∏è. –ü—Ä–∏—à–ª–∏ –º–Ω–µ –≤ –æ—Ç–≤–µ—Ç —Ç–æ–ª—å–∫–æ —Ç–µ–ª–æ –æ—Ç—á–µ—Ç–∞ –≤ –≤–∏–¥–µ —Ç–µ–∫—Å—Ç–∞ –∏–ª–∏ .txt —Ñ–∞–π–ª–∞. –í–µ—Å—å —Ç–µ–∫—Å—Ç –¥–æ–ª–∂–µ–Ω –±—ã—Ç—å –±–µ–∑ –æ—Ñ–æ—Ä–º–ª–µ–Ω–∏—è
            
            4Ô∏è. –ü–æ–¥–æ–∂–¥–∏, –ø–æ–∫–∞ —è –∑–∞–∫–æ–Ω—á—É –∞–Ω–∞–ª–∏–∑ –∏ –æ—Ç–ø—Ä–∞–≤–ª—é —Ä–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏–∏ –ø–æ –∏—Å–ø—Ä–∞–≤–ª–µ–Ω–∏—é —Å –≥–æ—Ç–æ–≤—ã–º –ø—Ä–∏–º–µ—Ä–æ–º
            
            
            ‚ö†Ô∏è –£—á—Ç–∏, —á—Ç–æ —è –Ω–µ —Å–æ–≤–µ—Ä—à–µ–Ω–µ–Ω –∏ –∏–Ω–æ–≥–¥–∞ –º–æ–≥—É –¥–∞–≤–∞—Ç—å –Ω–µ–ø—Ä–∞–≤–∏–ª—å–Ω—ã–µ –∏–ª–∏ —Å—Ç—Ä–∞–Ω–Ω—ã–µ —Ä–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏–∏. 
            –í–æ—Å–ø—Ä–∏–Ω–∏–º–∞–π –º–æ–∏ –∑–∞–º–µ—á–∞–Ω–∏—è –ø—Ä–æ—Å—Ç–æ –∫–∞–∫ –ø–æ–∂–µ–ª–∞–Ω–∏—è –∫ –∏—Å–ø—Ä–∞–≤–ª–µ–Ω–∏—é, –∞ –Ω–µ –∫–∞–∫ —Å—Ç—Ä–æ–≥–∏–µ —Ç—Ä–µ–±–æ–≤–∞–Ω–∏—è.
            –ü–æ–ª—å–∑—É–π—Å—è –ø—Ä–∏–Ω—Ü–∏–ø–æ–º **'–¥–æ–≤–µ—Ä—è–π, –Ω–æ –ø—Ä–æ–≤–µ—Ä—è–π'**
                
                
            ‚öôÔ∏è **–û—Å–æ–±–µ–Ω–Ω–æ—Å—Ç–∏ –≤–∑–∞–∏–º–æ–¥–µ–π—Å—Ç–≤–∏—è:**
            
            - –Ø —Ä–∞–±–æ—Ç–∞—é –ø–æ –ø—Ä–∏–Ω—Ü–∏–ø—É '—Å–µ—Å—Å–∏–∏' –∏ –∑–∞–ø–æ–º–∏–Ω–∞—é –∫–æ–Ω—Ç–µ–∫—Å—Ç
            
            - –£ —Ç–µ–±—è –±—É–¥–µ—Ç –æ–ø—Ä–µ–¥–µ–ª–µ–Ω–Ω–æ–µ –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –ø–æ–ø—ã—Ç–æ–∫, –ø—Ä–µ–∂–¥–µ —á–µ–º —Å–µ—Å—Å–∏—è –±—É–¥–µ—Ç –∑–∞–∫—Ä—ã—Ç–∞
            
            - –ï—Å–ª–∏ —Å–µ—Å—Å–∏—è –∑–∞–≤–µ—Ä—à–µ–Ω–∞, –∞ —Ç—ã –µ—â–µ –Ω–µ –∑–∞–∫–æ–Ω—á–∏–ª, —Ç–æ –ø—Ä–æ—Å—Ç–æ –Ω–∞—á–Ω–∏ –Ω–æ–≤—É—é, –∑–∞–ø—É—Å—Ç–∏–≤ –µ—â–µ –æ–¥–Ω—É –ø—Ä–æ–≤–µ—Ä–∫—É
            
            
            üí° –ï—Å–ª–∏ —è –Ω–µ –æ—Ç–≤–µ—á–∞—é –∏–ª–∏ –≤—ã–¥–∞—é –æ—à–∏–±–∫—É ‚Äî –ø–æ–ø—Ä–æ–±—É–π –ø–æ–∑–∂–µ –∏–ª–∏ –Ω–∞–ø–∏—à–∏ <@337950212016439327> –¥–ª—è –ø–æ–º–æ—â–∏"

  start:
    description:
      text: "üëã –ü—Ä–∏–≤–µ—Ç! –û—Ç–ø—Ä–∞–≤—å —Å—é–¥–∞ —Ç–æ–ª—å–∫–æ —Ç–µ–ª–æ –æ—Ç—á–µ—Ç–∞ –≤ –≤–∏–¥–µ **—Ç–µ–∫—Å—Ç–∞** –∏–ª–∏ **.txt-—Ñ–∞–π–ª–∞**. 
            –û–±—Ä–∞—Ç–∏ –≤–Ω–∏–º–∞–Ω–∏–µ, —á—Ç–æ —Ç–µ–∫—Å—Ç –¥–æ–ª–∂–µ–Ω –±—ã—Ç—å –±–µ–∑ –∫–∞–∫–æ–≥–æ-–ª–∏–±–æ –æ—Ñ–æ—Ä–º–ª–µ–Ω–∏—è –∏–ª–∏ –∫–æ–¥–∞
            
            
            ‚ö†Ô∏è –Ø –º–æ–≥—É –æ—à–∏–±–∞—Ç—å—Å—è, –ø–æ—ç—Ç–æ–º—É –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ –≤—Å–µ –ø–µ—Ä–µ–ø—Ä–æ–≤–µ—Ä—å –ø–µ—Ä–µ–¥ –ø—É–±–ª–∏–∫–∞—Ü–∏–µ–π –æ—Ç—á–µ—Ç–∞!"

  start_notify:
    description:
      text: "‚úÖ –Ø –Ω–∞–ø–∏—Å–∞–ª —Ç–µ–±–µ –≤ –õ–° - –ø—Ä–æ–≤–µ—Ä—å —Å–æ–æ–±—â–µ–Ω–∏—è"

  check_started:
    description:
      text: "ü§ñ –Ø –∞–Ω–∞–ª–∏–∑–∏—Ä—É—é —Ç–≤–æ–π –æ—Ç—á–µ—Ç. –ú–Ω–µ –ø–æ—Ç—Ä–µ–±—É–µ—Ç—Å—è –Ω–µ–∫–æ—Ç–æ—Ä–æ–µ –≤—Ä–µ–º—è..."

  err_pls_wait:
    description:
      text: "‚è≥ –û—Ç—á–µ—Ç —É–∂–µ –æ—Ç–ø—Ä–∞–≤–ª–µ–Ω –∏ –∞–Ω–∞–ª–∏–∑–∏—Ä—É–µ—Ç—Å—è. –î–æ–∂–¥–∏—Å—å –æ–∫–æ–Ω—á–∞–Ω–∏—è —Ç–µ–∫—É—â–µ–π –ø—Ä–æ–≤–µ—Ä–∫–∏"

  err_limit_reached:
    description:
      text: "üö´ –õ–∏–º–∏—Ç –ø—Ä–æ–≤–µ—Ä–æ–∫ –∏—Å—á–µ—Ä–ø–∞–Ω. –°–µ—Å—Å–∏—è –∑–∞–≤–µ—Ä—à–µ–Ω–∞. 
            –ü–µ—Ä–µ–π–¥–∏ –≤ –∫–∞–Ω–∞–ª –∏ –Ω–∞–∂–º–∏ –Ω–∞ –∫–Ω–æ–ø–∫—É, —á—Ç–æ–±—ã –Ω–∞—á–∞—Ç—å –Ω–æ–≤—É—é"

  err_dm_closed:
    description:
      text: "‚ùå –Ø –Ω–µ –º–æ–≥—É –Ω–∞–ø–∏—Å–∞—Ç—å —Ç–µ–±–µ –≤ –ª–∏—á–Ω—ã–µ —Å–æ–æ–±—â–µ–Ω–∏—è. –†–∞–∑—Ä–µ—à–∏ –õ–° –∏ –ø–æ–ø—Ä–æ–±—É–π —Å–Ω–æ–≤–∞"

  err_wrong_format:
    description:
      text: "‚ùå –ü—Ä–∏—à–ª–∏ —Ñ–∞–π–ª –≤ .txt —Ñ–æ—Ä–º–∞—Ç–µ"

  err_wrong_file_input:
    description:
      text: "‚ùå –ù–µ —É–¥–∞–ª–æ—Å—å –ø—Ä–æ—á–∏—Ç–∞—Ç—å –æ—Ç—á–µ—Ç. –ü—Ä–æ–≤–µ—Ä—å, —Å–æ–¥–µ—Ä–∂–∏–º–æ–µ –æ—Ç–ø—Ä–∞–≤–ª—è–µ–º–æ–≥–æ —Ñ–∞–π–ª–∞ –∏ –ø–æ–ø—Ä–æ–±—É–π –µ—â–µ —Ä–∞–∑"

  err_inactive_session:
    description:
      text: "‚ùå –£ —Ç–µ–±—è –Ω–µ—Ç –∞–∫—Ç–∏–≤–Ω–æ–π —Å–µ—Å—Å–∏–∏. –ü–µ—Ä–µ–π–¥–∏ –≤ –∫–∞–Ω–∞–ª —Å –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–æ–º –±–æ—Ç–∞ –∏ –Ω–∞–∂–º–∏ –Ω–∞ –∫–Ω–æ–ø–∫—É"

  err_exception:
    description:
      text: "‚ùå –ü—Ä–æ–∏–∑–æ—à–ª–∞ –Ω–µ–∏–∑–≤–µ—Å—Ç–Ω–∞—è –æ—à–∏–±–∫–∞:"

  err_already_started:
    description:
      text: "‚ö†Ô∏è –£ —Ç–µ–±—è —É–∂–µ –µ—Å—Ç—å –∞–∫—Ç–∏–≤–Ω–∞—è –ø—Ä–æ–≤–µ—Ä–∫–∞. –ó–∞–π–¥–∏ –≤ –õ–° —Å–æ –º–Ω–æ–π"

  err_too_many_clients:
    description:
      text: "‚ö†Ô∏è –°–µ–π—á–∞—Å —Å–ª–∏—à–∫–æ–º –º–Ω–æ–≥–æ –∞–∫—Ç–∏–≤–Ω—ã—Ö –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –∏ –Ω–µ—Ç —Å–≤–æ–±–æ–¥–Ω–æ–π —Å–µ—Å—Å–∏–∏. –ü–æ–ø—Ä–æ–±—É–π –ø–æ–∑–∂–µ"

  session_closed_ok:
    description:
      text: "‚úÖ –°–µ—Å—Å–∏—è –∑–∞–≤–µ—Ä—à–µ–Ω–∞"

  session_closed_by_timeout:
    description:
      text: "‚è∞ –°–µ—Å—Å–∏—è –∑–∞–≤–µ—Ä—à–µ–Ω–∞ –∞–≤—Ç–æ–º–∞—Ç–∏—á–µ—Å–∫–∏ –∏–∑-–∑–∞ –ø—Ä–æ—Å—Ç–æ—è. 
            –ß—Ç–æ–±—ã –Ω–∞—á–∞—Ç—å –Ω–æ–≤—É—é –ø—Ä–æ–≤–µ—Ä–∫—É, –≤–µ—Ä–Ω–∏—Å—å –≤ –∫–∞–Ω–∞–ª —Å –∏–Ω—Ç–µ—Ä—Ñ–µ–π—Å–æ–º –±–æ—Ç–∞ –∏ –Ω–∞–∂–º–∏ –Ω–∞ –∫–Ω–æ–ø–∫—É"
