message:
  initial:
    title:
      text: "–ê—Å—Å–∏—Å—Ç–µ–Ω—Ç –¥–ª—è –ø—Ä–æ–≤–µ—Ä–∫–∏ –æ—Ç—á–µ—Ç–æ–≤"
      color: 0x3498db
    description:
      text: "üëã –Ø - –±–æ—Ç, –∫–æ—Ç–æ—Ä—ã–π –∏—Å–ø–æ–ª—å–∑—É–µ—Ç –ò–ò –¥–ª—è –ø—Ä–æ–≤–µ—Ä–∫–∏ –æ—Ç—á–µ—Ç–æ–≤.
            –¢—ã –º–æ–∂–µ—à—å –∏—Å–ø–æ–ª—å–∑–æ–≤–∞—Ç—å –º–µ–Ω—è, —á—Ç–æ–±—ã –≤—ã–ø–æ–ª–Ω–∏—Ç—å —Å–∞–º–æ–ø—Ä–æ–≤–µ—Ä–∫—É –ø–µ—Ä–µ–¥ –ø—É–±–ª–∏–∫–∞—Ü–∏–µ–π –æ—Ç—á–µ—Ç–∞. 
            –≠—Ç–æ –ø–æ–º–æ–∂–µ—Ç —Å–Ω–∏–∑–∏—Ç—å –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –≤–æ–ø—Ä–æ—Å–æ–≤ –∫–∞–∫ —É —Ç–≤–æ–µ–≥–æ —Å—É–ø–µ—Ä–≤–∞–π–∑–µ—Ä–∞, —Ç–∞–∫ –∏ —É –û–í–†


            ‚ö†Ô∏è –£—á—Ç–∏, —á—Ç–æ —è –Ω–µ —Å–æ–≤–µ—Ä—à–µ–Ω–µ–Ω –∏ –∏–Ω–æ–≥–¥–∞ –º–æ–≥—É –¥–∞–≤–∞—Ç—å –Ω–µ–ø—Ä–∞–≤–∏–ª—å–Ω—É—é –æ—Ü–µ–Ω–∫—É. 
            –í–æ—Å–ø—Ä–∏–Ω–∏–º–∞–π –º–æ–∏ –∑–∞–º–µ—á–∞–Ω–∏—è –∫–∞–∫ —Ä–µ–∫–æ–º–µ–Ω–¥–∞—Ü–∏–∏, –∞ –Ω–µ —Ç—Ä–µ–±–æ–≤–∞–Ω–∏—è.
            –ü–æ–ª—å–∑—É–π—Å—è –ø—Ä–∏–Ω—Ü–∏–ø–æ–º **–¥–æ–≤–µ—Ä—è–π, –Ω–æ –ø—Ä–æ–≤–µ—Ä—è–π**


            ‚ÑπÔ∏è –ï—Å–ª–∏ —Ç—ã —Å—Ç–æ–ª–∫–Ω—É–ª—Å—è —Å –æ—à–∏–±–∫–∞–º–∏, —Ö–æ—á–µ—à—å –ø—Ä–µ–¥–ª–æ–∂–∏—Ç—å —É–ª—É—á—à–µ–Ω–∏—è –∏–ª–∏ –ø–æ–ª—É—á–∏—Ç—å –ø–æ–º–æ—â—å - 
            –Ω–∞–ø–∏—à–∏ –≤ –õ–° <@337950212016439327>


            ‚¨áÔ∏è –ù–∞–∂–º–∏ **–ù–∞—á–∞—Ç—å –ø—Ä–æ–≤–µ—Ä–∫—É**, —á—Ç–æ–±—ã –ø—Ä–∏—Å—Ç—É–ø–∏—Ç—å, –∏–ª–∏ **–ò–Ω—Å—Ç—Ä—É–∫—Ü–∏—è**, —á—Ç–æ–±—ã —É–∑–Ω–∞—Ç—å, –∫–∞–∫ —ç—Ç–æ —Ä–∞–±–æ—Ç–∞–µ—Ç"
    image:
      url: "https://i.ibb.co/MxKqyByh/Ai-Report-Helper.png"
    button:
      start:
        label: "–ù–∞—á–∞—Ç—å –ø—Ä–æ–≤–µ—Ä–∫—É"
      help:
        label: "–ò–Ω—Å—Ç—Ä—É–∫—Ü–∏—è"


